import { Button } from "@/components/ui/button";
import { getValueById } from "@/data/values";
import { Trophy, Download, RotateCcw, Sparkles } from "lucide-react";
import { cn } from "@/lib/utils";

interface ResultsStepProps {
  rankedValues: string[];
  onRestart: () => void;
}

const ResultsStep = ({ rankedValues, onRestart }: ResultsStepProps) => {
  const handleDownload = () => {
    const values = rankedValues.map((id, index) => {
      const value = getValueById(id);
      return `${index + 1}. ${value?.name}: ${value?.description}`;
    });

    const content = `My Core Values\n${"=".repeat(40)}\n\n${values.join("\n\n")}\n\n---\nGenerated by Values Assessment Tool`;
    
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "my-core-values.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="animate-fade-in">
      <div className="text-center mb-10">
        <div className="w-20 h-20 rounded-full bg-accent/20 flex items-center justify-center mx-auto mb-6">
          <Trophy className="w-10 h-10 text-accent" />
        </div>
        <h2 className="font-heading text-3xl md:text-4xl font-bold text-foreground mb-3">
          Your Core Values
        </h2>
        <p className="text-muted-foreground max-w-xl mx-auto">
          These are the values that define who you are at your core. 
          Use them as a compass for making decisions and living authentically.
        </p>
      </div>

      <div className="max-w-2xl mx-auto space-y-4 mb-10">
        {rankedValues.map((valueId, index) => {
          const value = getValueById(valueId);
          if (!value) return null;

          const isTop = index === 0;

          return (
            <div
              key={value.id}
              className={cn(
                "glass-panel p-6 animate-fade-in-up relative overflow-hidden",
                isTop && "border-accent/50"
              )}
              style={{ animationDelay: `${index * 150}ms` }}
            >
              {isTop && (
                <div className="absolute top-0 right-0 bg-accent text-accent-foreground px-3 py-1 text-xs font-semibold rounded-bl-lg flex items-center gap-1">
                  <Sparkles className="w-3 h-3" />
                  Primary Value
                </div>
              )}
              
              <div className="flex items-start gap-5">
                <div 
                  className={cn(
                    "flex-shrink-0 w-12 h-12 rounded-xl flex items-center justify-center text-xl font-bold",
                    isTop 
                      ? "bg-accent text-accent-foreground" 
                      : "bg-primary/10 text-primary"
                  )}
                >
                  {index + 1}
                </div>
                
                <div className="flex-1">
                  <h3 className="font-heading text-xl font-bold text-foreground mb-2">
                    {value.name}
                  </h3>
                  <p className="text-muted-foreground leading-relaxed">
                    {value.description}
                  </p>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      <div className="glass-panel p-6 max-w-2xl mx-auto mb-8">
        <h3 className="font-heading text-lg font-semibold text-foreground mb-3">
          Reflection Questions
        </h3>
        <ul className="space-y-2 text-muted-foreground">
          <li className="flex items-start gap-2">
            <span className="text-primary mt-1">•</span>
            How do these values show up in your daily decisions?
          </li>
          <li className="flex items-start gap-2">
            <span className="text-primary mt-1">•</span>
            Are there areas of your life where you're not honoring these values?
          </li>
          <li className="flex items-start gap-2">
            <span className="text-primary mt-1">•</span>
            How might these values guide your leadership style?
          </li>
        </ul>
      </div>

      <div className="flex flex-col sm:flex-row gap-4 justify-center">
        <Button variant="outline" size="lg" onClick={handleDownload} className="gap-2">
          <Download className="w-5 h-5" />
          Download Results
        </Button>
        <Button variant="subtle" size="lg" onClick={onRestart} className="gap-2">
          <RotateCcw className="w-5 h-5" />
          Start Over
        </Button>
      </div>
    </div>
  );
};

export default ResultsStep;
