import { useNavigate } from "react-router-dom";
import { Download, Edit3, RefreshCw, CheckCircle, Brain, ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { StoredValue } from "@/hooks/useLocalStorage";

interface ValuesCompleteProps {
  values: StoredValue[];
  onStartOver: () => void;
  onEditManually: () => void;
}

const ValuesComplete = ({ values, onStartOver, onEditManually }: ValuesCompleteProps) => {
  const navigate = useNavigate();

  const handleDownload = () => {
    const content = values
      .map((v, i) => `${i + 1}. ${v.name}${v.description ? `\n   ${v.description}` : ""}`)
      .join("\n\n");
    
    const fullContent = `My Core Values\n${"=".repeat(20)}\n\n${content}\n\n---\nGenerated by Values Compass\n${new Date().toLocaleDateString()}`;
    
    const blob = new Blob([fullContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "my-core-values.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-8 text-center">
      {/* Success message */}
      <div className="py-8">
        <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-primary/10 mb-6">
          <CheckCircle className="h-8 w-8 text-primary" aria-hidden="true" />
        </div>
        
        <h2 className="text-2xl font-heading font-bold text-foreground mb-3">
          Your core values are saved
        </h2>
        <p className="text-muted-foreground max-w-md mx-auto">
          These {values.length} values will guide your reflections and help you check decisions against what matters most.
        </p>
      </div>

      {/* Values list */}
      <section className="max-w-md mx-auto" aria-labelledby="core-values-heading">
        <h3 id="core-values-heading" className="sr-only">Your core values</h3>
        <ol className="space-y-3 text-left">
          {values.map((value, index) => (
            <li key={value.id} className="calm-card flex items-start gap-4">
              <span
                className="flex-shrink-0 w-8 h-8 rounded-full bg-primary/10 flex items-center justify-center text-sm font-bold text-primary"
                aria-hidden="true"
              >
                {index + 1}
              </span>
              <div>
                <span className="font-medium block">{value.name}</span>
                {value.description && (
                  <span className="text-sm text-muted-foreground">{value.description}</span>
                )}
              </div>
            </li>
          ))}
        </ol>
      </section>

      {/* Download */}
      <Button variant="outline" onClick={handleDownload}>
        <Download className="h-4 w-4 mr-2" aria-hidden="true" />
        Download my values
      </Button>

      {/* Next steps */}
      <section className="pt-8 border-t border-border" aria-labelledby="next-steps-heading">
        <h3 id="next-steps-heading" className="text-lg font-heading font-bold mb-6">
          What would you like to do next?
        </h3>
        
        <div className="grid sm:grid-cols-2 gap-4 max-w-lg mx-auto">
          <button
            onClick={() => navigate("/decisions")}
            className="calm-card text-left hover:ring-2 hover:ring-primary transition-all group"
          >
            <CheckCircle className="h-6 w-6 text-primary mb-3" aria-hidden="true" />
            <h4 className="font-medium mb-1 group-hover:text-primary transition-colors">
              Decision Alignment
            </h4>
            <p className="text-sm text-muted-foreground">
              Explore value trade-offs in your choices
            </p>
            <ArrowRight className="h-4 w-4 text-muted-foreground mt-3 group-hover:translate-x-1 transition-transform" aria-hidden="true" />
          </button>
          
          <button
            onClick={() => navigate("/reflections")}
            className="calm-card text-left hover:ring-2 hover:ring-primary transition-all group"
          >
            <Brain className="h-6 w-6 text-accent mb-3" aria-hidden="true" />
            <h4 className="font-medium mb-1 group-hover:text-primary transition-colors">
              Micro reflection
            </h4>
            <p className="text-sm text-muted-foreground">
              Take a moment for quick awareness
            </p>
            <ArrowRight className="h-4 w-4 text-muted-foreground mt-3 group-hover:translate-x-1 transition-transform" aria-hidden="true" />
          </button>
        </div>
      </section>

      {/* Edit options */}
      <div className="flex flex-wrap justify-center gap-3 pt-6">
        <Button variant="ghost" onClick={onEditManually}>
          <Edit3 className="h-4 w-4 mr-2" aria-hidden="true" />
          Edit values
        </Button>
        <Button variant="ghost" onClick={onStartOver}>
          <RefreshCw className="h-4 w-4 mr-2" aria-hidden="true" />
          Start over
        </Button>
      </div>
    </div>
  );
};

export default ValuesComplete;
